/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform --types checkered_tile_floor.glb
Files: checkered_tile_floor.glb [1.35MB] > C:\Users\mouli\r3f-webgpu\public\checkered_tile_floor-transformed.glb [78.78KB] (94%)
Author: Andrew Jepson (https://sketchfab.com/ajepson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/checkered-tile-floor-e6c5ea5c0c8f4c9ba27f07dcb9091ffd
Title: Checkered Tile Floor
*/

import * as THREE from "three";
import { useEffect } from "react";
import type { ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { usePhysics } from "../physics/context";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    floor_texture: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Floor(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/checkered_tile_floor-transformed.glb",
  ) as unknown as GLTFResult;

  const engine = usePhysics();

  useEffect(() => {
    const groundShape = engine.createBox({
      width: 1000,
      height: 2,
      depth: 1000,
    });

    const body = engine.createStaticBody({
      shape: groundShape,
      position: { x: 0, y: -10, z: 0 },
      orientation: { x: 0, y: 0, z: 0, w: 1 },
      friction: 1,
      restitution: 0,
    });

    return () => {
      engine.destroyBody(body);
      engine.destroyShape(groundShape);
    };
  }, [engine]);

  return (
    <group
      {...props}
      dispose={null}
      rotation={[Math.PI / 2, 0, 0]}
      position={[0, -10, 0]}
    >
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Object_2.geometry}
        material={materials.floor_texture}
        scale={1}
      />
    </group>
  );
}

useGLTF.preload("/models/checkered_tile_floor-transformed.glb");
