/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --types --instance road.glb
Files: road.glb [9.27MB] > C:\Users\mouli\racing-kit\public\road-transformed.glb [455.89KB] (95%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useEffect, useRef } from "react";
import type { ThreeElements } from "@react-three/fiber";
import type { GLTF } from "three-stdlib";
import { usePhysics } from "../physics/context";

type GLTFResult = GLTF & {
  nodes: {
    Object_424: THREE.Mesh;
    Object_460: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_30: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Model(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/road-transformed.glb",
  ) as unknown as GLTFResult;
  const colliderMeshRef = useRef<THREE.Mesh>(null);
  const engine = usePhysics();

  useEffect(() => {
    const colliderMesh = colliderMeshRef.current;

    if (!colliderMesh) {
      return;
    }

    colliderMesh.updateWorldMatrix(true, false);

    const colliderGeometry = colliderMesh.geometry.clone();
    colliderGeometry.applyMatrix4(colliderMesh.matrixWorld);

    const shape = engine.createTriangleMeshFromGeometry(colliderGeometry);
    colliderGeometry.dispose();

    const body = engine.createStaticBody({ shape });

    return () => {
      engine.destroyBody(body);
      engine.destroyShape(shape);
    };
  }, [engine]);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={colliderMeshRef}
        castShadow
        receiveShadow
        geometry={nodes.Object_424.geometry}
        material={materials["Material.003"]}
        position={[-11.927, 1.057, -20.465]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_460.geometry}
        material={materials.material_0}
        position={[8.196, 0.748, 5.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials["Material.001"]}
        position={[-4.548, 0.88, -17.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials["Material.002"]}
        position={[-4.505, 0.675, -17.037]}
      />
    </group>
  );
}

useGLTF.preload("/models/road-transformed.glb");
