/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --types vehicle-truck-yellow.glb
*/

import * as THREE from "three";
import { useEffect, useMemo } from "react";
import type { Ref } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";
import type { GLTF } from "three-stdlib";
import { MeshStandardNodeMaterial } from "three/webgpu";
import { texture } from "three/tsl";

type GLTFResult = GLTF & {
  nodes: {
    underside: THREE.Mesh;
    ["wheel-back-left"]: THREE.Mesh;
    ["wheel-back-right"]: THREE.Mesh;
    ["wheel-front-left"]: THREE.Mesh;
    ["wheel-front-right"]: THREE.Mesh;
    body: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export type VehicleMeshRefs = {
  underside?: Ref<THREE.Mesh>;
  body?: Ref<THREE.Mesh>;
  wheelFrontLeft?: Ref<THREE.Mesh>;
  wheelFrontRight?: Ref<THREE.Mesh>;
  wheelBackLeft?: Ref<THREE.Mesh>;
  wheelBackRight?: Ref<THREE.Mesh>;
};

type VehicleProps = ThreeElements["group"] & {
  meshRefs?: VehicleMeshRefs;
};

export function Vehicle({ meshRefs, ...props }: VehicleProps) {
  const { nodes, materials } = useGLTF(
    "/models/vehicle-truck-yellow.glb",
  ) as unknown as GLTFResult;
  const colormapTexture = useTexture("/textures/colormap.png");

  const vehicleMaterial = useMemo(() => {
    const material = new MeshStandardNodeMaterial({
      metalness: materials.colormap.metalness,
      roughness: materials.colormap.roughness,
    });

    material.colorNode = texture(colormapTexture);

    return material;
  }, [
    colormapTexture,
    materials.colormap.metalness,
    materials.colormap.roughness,
  ]);

  useEffect(() => {
    colormapTexture.colorSpace = THREE.SRGBColorSpace;
    colormapTexture.flipY = false;
    colormapTexture.needsUpdate = true;
  }, [colormapTexture]);

  useEffect(() => {
    return () => {
      vehicleMaterial.dispose();
    };
  }, [vehicleMaterial]);

  return (
    <group {...props} dispose={null} scale={1} rotation={[0, 0, 0]}>
      <mesh
        ref={meshRefs?.underside}
        castShadow
        receiveShadow
        geometry={nodes.underside.geometry}
        material={vehicleMaterial}
        position={[0, 0.3, 0.1]}
      />
      <mesh
        ref={meshRefs?.wheelBackLeft}
        castShadow
        receiveShadow
        geometry={nodes["wheel-back-left"].geometry}
        material={vehicleMaterial}
        position={[0.55, 0.3, -0.657]}
      />
      <mesh
        ref={meshRefs?.wheelBackRight}
        castShadow
        receiveShadow
        geometry={nodes["wheel-back-right"].geometry}
        material={vehicleMaterial}
        position={[-0.55, 0.3, -0.657]}
      />
      <mesh
        ref={meshRefs?.wheelFrontLeft}
        castShadow
        receiveShadow
        geometry={nodes["wheel-front-left"].geometry}
        material={vehicleMaterial}
        position={[0.55, 0.3, 0.857]}
      />
      <mesh
        ref={meshRefs?.wheelFrontRight}
        castShadow
        receiveShadow
        geometry={nodes["wheel-front-right"].geometry}
        material={vehicleMaterial}
        position={[-0.55, 0.3, 0.857]}
      />
      <mesh
        ref={meshRefs?.body}
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={vehicleMaterial}
        position={[0, 0.4, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicle-truck-yellow.glb");
